name: "DataOps: Infrastructure CI/CD Gate"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Force the runner execution environment to prioritize the Node.js 24 engine
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  terraform-spec-validation:
    name: "Lint & Validate Structural Architecture"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform Binary
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initialize Configuration Environments
        run: terraform -chdir=terraform init -backend=false

      - name: Static Layout Compliance Check
        run: terraform -chdir=terraform fmt -check

      - name: Declarative Syntax Evaluation
        run: terraform -chdir=terraform validate